# Generated by Django 6.0.1 on 2026-01-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0002_alter_movie_director_alter_movie_has_subtitles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='has_subtitles',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
