# Generated by Django 6.0.1 on 2026-01-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapp', '0003_alter_movie_has_subtitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.FileField(blank=True, upload_to='posters'),
        ),
    ]
